### ISSUE TITLE
Exporting and then importing bookmarks breaks jhove validation

### ISSUE THREAD

**Issue by a-vrma** [johnwhitington/cpdf-source#194]
## Description

Exporting and then importing bookmarks (without changing anything) breaks jhove validation.

## Steps to reproduce

1. `cpdf mwe.pdf -list-bookmarks >b.txt`
2. `cpdf mew.pdf -add-bookmarks b.txt -o fin.pdf`
3. `jhove -m pdf-hul fin.pdf`

The output is
```
Jhove (Rel. 1.24.1, 2020-03-16)
 Date: 2020-05-03 00:59:02 EDT
 RepresentationInformation: fin.pdf
  ReportingModule: PDF-hul, Rel. 1.12.2 (2019-12-10)
  LastModified: 2020-05-03 00:51:22 EDT
  Size: 111344
  Format: PDF
  Status: Not well-formed
  SignatureMatches:
   PDF-hul
  ErrorMessage: Invalid object number in cross-reference stream
   ID: PDF-HUL-80
   Offset: 111313
  MIMEtype: application/pdf
```

The original file, [mwe.pdf], validates fine. It was created with PDFLaTeX and hyperref.

[mwe.pdf]: <https://github.com/johnwhitington/cpdf-source/files/4569638/mwe.pdf>
